### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by oogienl** [qalle-fivem/esx-qalle-jail#8]
everytime a player enters the game im getting a spam message in the console, and i am wondering how i can fix this, the resource seems to work just fine its just spamming the console. here is the message:

Error running call reference function for resource esx-qalle-jail: citizen:/scripting/lua/scheduler.lua:403: server/server.lua:125: attempt to compare number with nil
stack traceback:
        server/server.lua:125: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error: Unhandled error: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:11
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:56:6)

**Comment by qalle-fivem** [comment]
Should be fixed.

**Comment by zabattaro** [comment]
Still dont fix. Im getting this too

**Comment by vejbuch** [comment]
i have same problem
